### ISSUE TITLE
clean up branches. 

### ISSUE THREAD

**Issue by kohlhase** [slatex/LaTeXML-Plugin-sTeX#128] opened 2019-09-18 09:53 UTC
we have 11 branches, which is ridiculous. Most of these are stale, but may have some useful work by Hang. 
I will try to find out which ones are still useful and which are not.

**Comment by kohlhase** [comment] 2019-11-15 08:13
I have done some work on this. most of the stale branches can probably just be deleded. I have done so for three now. I am updating them with master, so we can see what they give us. 

The `mmt` branch seems to be old work on the stex-mmt-stex integration.

**Comment by kohlhase** [comment] 2019-11-15 08:48
There is still one branch called upstream-latexl, by @tkw1536 that needs looking at. Does it have anything worth keeping? If so, please merge in master (and possibly make a pull request).

**Comment by tkw1536** [comment] 2019-11-16 18:29
I want to start looking at that branch early next week, in particular ensuring that the basic testcases work as intended with upstream LaTeXML before working on any of the new features.

**Comment by kohlhase** [comment] 2019-12-10 05:38
I have done my part, re-assigning to @tkw1536

**Comment by tkw1536** [comment] 2019-12-17 05:14
With #145 merged, I removed the 'newtests' and branches I felt directly responsible for. @Jazzpirate can we also delete the 'dennis' branch?

**Comment by kohlhase** [comment] 2019-12-17 07:45
I have rebased my branches ,and that seems to conclude the issue

**Comment by kohlhase** [comment] 2019-12-17 07:50
sorry, there is still Tom's `upstream-latexml` branch that needs looking at

**Comment by tkw1536** [comment] 2019-12-17 15:07
That has been integrated indirectly into the new tests already. I simply forgot to delete it.

**Closed by tkw1536** 2019-12-17 15:07 UTC
